prometheus:
  image: prom/prometheus:v2.33.3
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: ClusterIP
    port: 9090

nodeExporter:
  image: prom/node-exporter:v1.3.1
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 32Mi

grafana:
  image: grafana/grafana:8.4.5
  adminUser: admin
  adminPassword: admin
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: ClusterIP
    port: 3000

