apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: {{ .Values.nodeExporter.image }}
          resources:
            {{- toYaml .Values.nodeExporter.resources | nindent 12 }}
          ports:
            - containerPort: 9100
              name: metrics
          args:
            - "--path.procfs=/host/proc"
            - "--path.sysfs=/host/sys"
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
      hostNetwork: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys

